### PR TITLE
Add GE 45856 light switch

### PR DESCRIPTION
**Pull request by mgsb**
Only supports on/off - device also reports electrical usage, but not supported yet.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by mgsb** [comment]
Thanks for fixing the description - it is, indeed, an in-wall device.

Any pointers on how to figure out retrieval of the electricity usage stats from the switch?

**Comment by Koenkk** [comment]
Can you post the contents of your `database.db`?

**Comment by mgsb** [comment]
[database.zip](https://github.com/Koenkk/zigbee-shepherd-converters/files/2739422/database.zip)

**Comment by Koenkk** [comment]
Can you try with:

```js
    {
        zigbeeModel: ['45856'],
        model: '45856GE',
        vendor: 'GE',
        description: 'In-wall smart switch',
        supports: 'on/off',
        fromZigbee: [fz.ignore_onoff_change, fz.generic_state],
        toZigbee: [tz.on_off, tz.ignore_transition],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
                (cb) => device.report('seMetering', 'instantaneousDemand', 0, 5, 1, cb),
            ];

            execute(device, actions, callback);
        },
    },
```

**Comment by mgsb** [comment]
Ok, that helps. I also added fromZigbee converters:

fromZigbee: [fz.ignore_onoff_change, fz.generic_state, fz.ignore_metering_change, fz.ENP_power],

I now get log entries like:
zigbee2mqtt:info 2019-1-9 18:17:41 MQTT publish: topic 'zigbee2mqtt/0x0022a300001c942f', payload '{"state":"ON","linkquality":0,"power":5492}'

I am using this in a hass.io runtime. I don't get the power attribute showing up in the entry for the switch. Do I need to do something to get the new power attribute recognized?

**Comment by Koenkk** [comment]
Home Assistant requires some modifications in zigbee2mqtt, I will do that once we have merged this in zigbee-shepherd-converters.

`5492` isn't a logical value, perhaps you need to divide it by 10. Is it realistic that the attached devices consumes 54.92 watt?

**Comment by mgsb** [comment]
I'm not sure what the scaling should be. I believe there is 15 LED bulbs at ~9w / bulb, so 55w seems too low. Tried googling for spec/datasheet but have not found anything yet.

**Pull request merged**
