### PR TITLE
Fix for device RTCGQ11LM wrong array with comma

### PR DESCRIPTION
**Pull request by dzungpv**
Fix for device RTCGQ11LM wrong array with comma, funny error :)

### CODE REVIEW

**Comment by dzungpv** [comment]
I edit on the web so lint failed, please re format because i am access to my MAC

**Comment by Koenkk** [comment]
The trailing comma is mandatory (because of eslint configuration)

**Comment by dzungpv** [comment]
@Koenkk I don't know why, before i remove the comma, my device could not connected, show receive data but not push to mqtt server, but it work fine after remove the comma.

**Comment by dzungpv** [comment]
May be slow in pairing, i close this now

**Pull request closed without merging**
