### PR TITLE
Osram Lightify Switch Mini Support

### PR DESCRIPTION
**Pull request by pixeldoc2000**
"Osram Lightify Switch Mini" (AC0251100NJ) Basic Support added.

https://github.com/Koenkk/zigbee2mqtt/issues/532

### CODE REVIEW

**Comment by pixeldoc2000** [comment]
I don't quite understand how the code handels device to be honest.

This Switch is very simular to Osram 4x EU-LIGHTIFY Switch (https://github.com/Koenkk/zigbee2mqtt/issues/159) only with tree Buttons.

grafik

So a "simple" `click` like Xiaomi / Aqara Switch is not suitable?

**Comment by pixeldoc2000** [comment]
Looking futher into the code for other devices i think i get what you mean by `click`.

Is a Switch by definition suppos to send a `click` and not an `action`? Is there documentation about what "device" is suppose to send which message?

> 
> 
> To keep it inline with other switches/buttons, could you change `action` to `click`?

Looks like this Device does not support double tab like xiaomi Switches for example. Only single press and hold.

How to support switches with multiple Buttons or what event to send? Could we do `click_button_1` oder `click_button_top` for example?

**Comment by pixeldoc2000** [comment]
How about this?
```javascript
    AC0251100NJ_on: {
        cid: 'genOnOff',
        type: 'cmdOn',
        convert: (model, msg, publish, options) => {
            return {click: 'on'};
            //return {click: 'up'};
            //return {action: 'on'};
            //return {action: 'up'};
        },
    },
    AC0251100NJ_off: {
        cid: 'genOnOff',
        type: 'cmdOff',
        convert: (model, msg, publish, options) => {
            return {click: 'off'};
            //return {click: 'down'};
            //return {action: 'off'};
            //return {action: 'down'};
        },
    },
    AC0251100NJ_on_hold: {
        cid: 'genLevelCtrl',
        type: 'cmdMoveWithOnOff',
        convert: (model, msg, publish, options) => {
            //return {click: 'on_hold'};
            return {action: 'on_hold'};
        },
    },
    AC0251100NJ_off_hold: {
        cid: 'genLevelCtrl',
        type: 'cmdMove',
        convert: (model, msg, publish, options) => {
            //return {click: 'off_hold'};
            return {action: 'off_hold'};
        },
    },
    AC0251100NJ_release: {
        cid: 'genLevelCtrl',
        type: 'cmdStop',
        convert: (model, msg, publish, options) => {
            return {action: 'release'};
        },
    },
```

**Comment by Koenkk** [comment]
In order to make integration with home automation software easier I propose the following.

If I'm right this buttons contains 3 buttons: up, down and circle.

This button will send two values: `brightness` (a value between 0 - 255) and `click`. 

Circle button will produce a `click: 'onoff'`.
The other two up/down buttons will change the value of the `brightness`; up will increase up to a max of 255, down will decrease up to a min of 0.

Don't worry about the code changes, we can reuse the code of the tradfri dimmer.

Can you check Circle CLICK (Button 2); it's strange that is produces nothing.

**Comment by pixeldoc2000** [comment]
Just to avoid misunderstanding:
grafik

This would be my preferred use case for this Switch right now:
Arrow UP - Single Click = ON
Arrow UP - Hold = Dimmer UP
Arrow DOWN - Single Click = OFF
Arrow DOWN - Hold = Dimmer DOWN
Dunno about the Circle Button yet.

Note: As stated above a Single Click on Circle does not send any Message, only Holding the Circle Key.

**Comment by Koenkk** [comment]
Arrow down/up seems strange to me for on/off. 

What is the behaviour when using it with the original bridge?

**Comment by Koenkk** [comment]
Closed due to inactivity

**Pull request closed without merging**
