### PR TITLE
Add Innr RS 128 T

### PR DESCRIPTION
**Pull request by FutureCow**
Add Innr RS 128 T GU10 Light Spot(On/Off, Dimmable, White spectrum)

### CODE REVIEW

**Comment by FutureCow** [comment]
What are the right values for color_temp and colorxy? Try to find out of color_temp or colorxy is used.

**Comment by Koenkk** [comment]
Color xy are RGB colors, does this bulb support it?

**Comment by FutureCow** [comment]
No, only colortemp. So everything is working nice!
The right value for the color_temp is from 200(blue) to 454(yellow)

**Comment by Koenkk** [comment]
ok, thanks!

**Pull request merged**
