### PR TITLE
Update devices.js to include support for Nue FB56+ZSW1HKJ1.7 2 gang s…

### PR DESCRIPTION
**Pull request by highground88**
Confirmed working for actuations only.

### CODE REVIEW

**Comment by highground88** [comment]
Sorry you are right. No MQTT message on pressing the switch. How do I determine what will need to be modified to do so?

Sending a valid MQTT message to turn on does result in feedback from the device, e.g. off returns the following state updates:

`2019-01-28 11:37:50Topic: zigbee2mqtt/2_gang_wall_switchQos: 0{"state":"on","device":{"ieeeAddr":"0x00124b0014afe1fb","friendlyName":"2_gang_wall_switch","type":"Router","nwkAddr":19115,"manufId":0,"manufName":"Feibit Inc co. ","powerSource":"Mains (single phase)","modelId":"FB56+ZSW1HKJ1.7","status":"offline"},"state_left":"off","state_right":"off"}`

Furthermore thank you for explaining the method re left/right labelling. As these switches are usually mounted vertically in Australia, I think I might change the "left/right" to "top/bottom", which allows for a "centre" or "middle" for the 3-gang, and might be less confusing.

**Comment by ryanbeaton** [comment]
Thanks for all your work on this. 

The button labeling can be confusing based on mounting style, especially the four button scene controller as, for example, top right will vary by mounting rotation. Might have to have notes in the devices section. 

Been very tempted to buy some and help out but put off by the reviews that they emit a strange hum that can be heard from two metres away! What is your experience.

**Comment by highground88** [comment]
Thanks Ryan. Personally I can't hear any humming - I don't have any in the bedroom yet but have 5 switches in the house so far, nothing noticeable. All seem relatively good considering the prices and alternatives. The app however is fairly average. Where are you located?

**Comment by ryanbeaton** [comment]
@highground88 I’m in PER

**Comment by highground88** [comment]
Shame.. I'm in BNE, would have dropped you one over to play with!

On Mon., 28 Jan. 2019, 5:48 pm Ryan Beaton <notifications@github.com<mailto:notifications@github.com> wrote:

@highground88<https://github.com/highground88> I’m in PER

**Comment by highground88** [comment]
Switch feedback! My only confusion is re the first 'state:', and whether 'fz.ignore_onoff_change' is needed or is causing issues. The state topic doesn't seem to reflect on whether left, right, both or none are on or off.

e.g: 

{"state":"OFF","linkquality":65,"state_left":"ON","state_right":"ON"}

{"state":"ON","linkquality":65,"state_left":"ON","state_right":"ON"}

{"state":"ON","linkquality":65,"state_left":"OFF","state_right":"ON"}

{"state":"OFF","linkquality":65,"state_left":"OFF","state_right":"OFF"}

{"state":"OFF","linkquality":65,"state_left":"ON","state_right":"OFF"}

**Comment by highground88** [comment]
Needs more work. Will open once confirmed all working.

**Pull request closed without merging**
