### PR TITLE
Bitron-Video Wall Thermostat

### PR DESCRIPTION
**Pull request by Chrischi-**
as discussed in #134 the new PR for the Bitron Wall thermostat.

fromZigbee:
`fz.bitron_thermostat_att_report `
`fz.bitron_thermostat_dev_change `
**both above result in this without "null" values. e.g.:**
_{
"local_temperature":20.2,
"local_temperature_calibration":0.4,
"occupied_heating_setpoint":21.5,
"linkquality":36,
"battery":"71.43",
"voltage":3000,
"running_state":1
}_
`fz.bitron_battery` **(works for all bitron battery powered devices)**

toZigbee:
`tz.thermostat_occupied_heating_setpoint` **(changed the calculation to use half degrees)**
`tz.thermostat_local_temperature_calibration`
`tz.thermostat_local_temperature`
`tz.thermostat_running_state` **(get the running state)**
`tz.thermostat_temperature_display_mode` **(set display mode to °C or °F)**

### CODE REVIEW

**Comment by Chrischi-** [comment]
shouldn't first the ecozy changes from @sebastianheierhoff merged?
it's the same and i would add the running_state and temp_mode_display to it.

@Koenkk 
how to get around the "Line xyz exceeds the maximum line length of 120  max-len" limit?

**Comment by sebastianheierhoff** [comment]
> @Koenkk
> how to get around the "Line xyz exceeds the maximum line length of 120 max-len" limit?

You need to break every line after 120 characters. Your IDE might be able to take care of this automatically.

**Comment by sebastianheierhoff** [comment]
@Chrischi-, thanks for your comments in my PR. I will add them today and also add your two converters.

**Comment by Chrischi-** [comment]
> @Chrischi-, thanks for your comments in my PR. I will add them today and also add your two converters.

i have the converter in my PR, you could / just have to add it at the documentation

**Comment by Chrischi-** [comment]
@sebastianheierhoff 
i tried that but didn't work with the bitron and so i didn't add it. I only create converters that I have successfully tested myself.

**Comment by sebastianheierhoff** [comment]
> @sebastianheierhoff
> i tried that but didn't work with the bitron and so i didn't add it. I only create converters that I have successfully tested myself.

Okay, I will try this with the ecozy, once your changes have been merged.

**Comment by Chrischi-** [comment]
> > @sebastianheierhoff
> > i tried that but didn't work with the bitron and so i didn't add it. I only create converters that I have successfully tested myself.
> 
> Okay, I will try this with the ecozy, once your changes have been merged.

x0000
TemperatureDisplayMode
enum8
0x00–0x01
RW
0x00 (Celsius)
0x02 (Fahrenheit)

The attribute is R/W so a "get" should be possible as well.

**Pull request merged**
