### PR TITLE
Support for WXKG02LM with modelId 'lumi.remote.b286acn01\u0000\u0000\u0000'

### PR DESCRIPTION
**Pull request by k3erg**
Discussion:
https://github.com/Koenkk/zigbee2mqtt/issues/329

### CODE REVIEW

**Comment by k3erg** [comment]
How to proceed?
- have two devices with the same name?
- somehow merge into existing device?
- add a suffix for devices with the same name?

**Comment by Koenkk** [comment]
Sorry for the late response.

I've merged it together with WXKG02LM, can you check if everything is OK? Then I will merge this.

**Comment by k3erg** [comment]
Great - yes, I can check it on Friday.

**Comment by k3erg** [comment]
That code was checked on an old and new type switch.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
