### PR TITLE
Cosmetic Fix for Blaupunkt SCM-S1 and Adding support Lupus 12031

### PR DESCRIPTION
**Pull request by mccoy88f**
Cosmetic Fix for Blaupunkt SCM-S1 (SCM-R_00.00.03.15TC) and Adding support Lupus 12031 (SCM_00.00.03.11TC)
Removed WarningDevice from Heiman (need more job on device to make it work)
Heiman M1 Door Sensor work but need a fix because now show inverted status (someone can help?)

### CODE REVIEW

**Comment by Koenkk** [comment]
When the contact is closed, contact should be `true`. Is this the case?

**Comment by mccoy88f** [comment]
Exact....

**Comment by Koenkk** [comment]
Try changing https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L1242 to `contact: !(zoneStatus & 1) > 0`

**Comment by mccoy88f** [comment]
Ok send this pull request for now

**Comment by Koenkk** [comment]
I don't see the PR, can you provide a link?

**Pull request merged**
