### PR TITLE
Added Salus thermostat

### PR DESCRIPTION
**Pull request by frozenwave11**
Added salus thermostat, still need to finish toZigbee. 

Help is more than welcomed

### CODE REVIEW

**Comment by Koenkk** [comment]
What still has to be done? Could @Chrischi- help maybe?

**Comment by frozenwave11** [comment]
Hi @Koenkk, I have finished device.js.
 FromZigbee  I used Ecozy thermostat inputes which works well.
ToZigbee I also tried Ecozy but I could only sent input for occupied_heating_setpoint.

Im struggling with setting fan mode, changing working mode(cooling/heating).
Also it would be great if it is possible to sent correct time and date to thermostat (it cannot be done directly on thermostat when it is online).
IF @Chrischi- is willing to help I can provide him anything he needs.

**Comment by Chrischi-** [comment]
I'am busy right now. Will look into it at the weekend.

**Comment by frozenwave11** [comment]
@Chrischi- sure, anytime you can. 

Thanks

**Comment by frozenwave11** [comment]
Hi @Chrischi- , maybe this can help, https://pastebin.com/AnfzY7wm . 
From this I can see:
- system_mode: 4 is heating mode
  - running_state: 0 - fan off.
  - running_state: 5 - fan low.
  - running_state: 33 - fan medium.
  - running_state: 65 - fan high.
- system_mode: 3 is cooling mode
  - running_state: 0 - fan off.
  - running_state: 6 - fan low.
  - running_state: 34 - fan medium.
  - running_state: 66 - fan high.
- running_mode: 4 heating?
- running_mode: 3 cooling?
- running_mode: 0 idle?

When I try different set/get messages:

Message
running_mode_get - https://pastebin.com/a1pyZMA9
for running_state - I got no converter available. 

Message
fan_mode_get - https://pastebin.com/9h16etWf
fan_mode_set - works 

Message:
system_mode_get - https://pastebin.com/hqiXwpgW
system_mode_set - https://pastebin.com/wsm6cJyQ

Message:
occupied_heating_setpoint_get - https://pastebin.com/ZZY44yDE
occupied_heating_setpoint_set and unoccupied_heating_setpoint - works,

Message
running_state_get - I got no converter available. 
running_state_set - I got no converter available. 

FILES:
toZigBee - https://pastebin.com/zUw3qAmZ
fromZigBee - https://pastebin.com/Q8byrUb2
devices - https://pastebin.com/05svigy5


So for me most important is to fix this error when I try to get different states from thermostat, fix issue with fan_mode and to make working thermostat changing from cooling to heating mode

sorry for such a long post
 and thanks a lot for helping

**Comment by Chrischi-** [comment]
@frozenwave11 
could you please update to the latest version? There are some nice commits that will help.
e.g. https://github.com/Koenkk/zigbee-shepherd-converters/commit/c7c9db1fbbee0ce6f3b5159fbcc2b159fd0dee33

What would you like to begin with? 
It would be best to post a new log (because of the update). But please post one after the other.

**Comment by frozenwave11** [comment]
Hi @Chrischi- , @Koenkk  I have update Zigbee2mqtt but, whatever I press on thermostat I have this error https://pastebin.com/M6bwAnwA.
I have copied everything from here  https://github.com/Koenkk/zigbee2mqtt/issues/917#issuecomment-456883921

Still doesn't work.

**Comment by Chrischi-** [comment]
> @Chrischi-
> yes I have.
> https://pastebin.com/s4LyWgVw

what exactly? 
npm install .... or copy & paste?

**Comment by frozenwave11** [comment]
@Chrischi-  
both, firstly I npm install, and when I run it I got error, then I copy and past.

Error - https://pastebin.com/MxYnaYtL

**Comment by Chrischi-** [comment]
I hope you know you need this, too. ;)

https://github.com/Koenkk/zcl-id/tree/salus

**Comment by frozenwave11** [comment]
@Chrischi- I know, I have add it again. I have unplugged raspberry. I will update you in 10 min is it fixed or not

**Comment by Chrischi-** [comment]
maybe you could join here: [Slack Channel](https://join.slack.com/t/zigbee2mqtt/shared_invite/enQtNTQwMzI4OTQxMzgwLWE0Y2E3OGNkZWJmNWRjZWY5MDQ0MzRjNjQ4OWYxNWU5NTViYWY4MTJmMzkxMGI5NDY5ZjQ1OGZmOTdlY2E3OGU) linke will expire in 1 day.

**Comment by dyrvigk** [comment]
Could any off you help me with wireless salus sq610  termostat i have tryed using the fc600 as base and get  somwhere but first problem is this in the log 
info  2020-09-04 10:37:45: 0x001e5e09025f4c40 (0x001e5e09025f4c40): SQ610RF - Salus Wireless thermostat (EndDevice)
warn  2020-09-04 10:37:45: `permit_join` set to  `true` in configuration.yaml.
warn  2020-09-04 10:37:45: Allowing new devices to join.
warn  2020-09-04 10:37:45: Set `permit_join` to `false` once you joined all devices.
info  2020-09-04 10:37:45: Zigbee: allowing new devices to join.
info  2020-09-04 10:37:45: Configuring '0x001e5e09025f4c40'
error 2020-09-04 10:37:45: Failed to configure '0x001e5e09025f4c40', attempt 1 (TypeError: shepherd.find is not a function
    at Object.configure (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\node_modules\zigbee-herdsman-converters\devices.js:2300:37)
    at Configure.configure (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\configure.js:143:45)
    at Configure.onZigbeeStarted (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\configure.js:111:28)
    at Controller.callExtensionMethod (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\controller.js:365:44))
info  2020-09-04 10:37:45: Connecting to MQTT server at mqtt://192.168.1.203
warn  2020-09-04 10:37:46: Device '0x001e5e09025f4c40' left the network
info  2020-09-04 10:37:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x001e5e09025f4c40"},"type":"device_removed"}'
info  2020-09-04 10:37:46: Connected to MQTT server
info  2020-09-04 10:37:46: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2020-09-04 10:37:46: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200805,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.14.4"}'
info  2020-09-04 10:37:55: Device '0x001e5e09025f4c40' joined
info  2020-09-04 10:37:55: Starting interview of '0x001e5e09025f4c40'
info  2020-09-04 10:37:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x001e5e09025f4c40"},"type":"device_connected"}'
info  2020-09-04 10:37:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x001e5e09025f4c40"},"type":"pairing"}'
info  2020-09-04 10:37:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001e5e09025f4c40"},"type":"device_announced"}'
error 2020-09-04 10:37:55: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\receive.js:120:42
    at Array.filter (<anonymous>)
    at Receive.onZigbeeEvent (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\receive.js:119:65)
    at Controller.callExtensionMethod (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\controller.js:365:44)
    at Controller.onZigbeeEvent (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\controller.js:254:14)
    at Zigbee.emit (events.js:315:20)
    at Controller.<anonymous> (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\zigbee.js:68:52)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\controller\controller.js:523:22)
    at Generator.next (<anonymous>))
error 2020-09-04 10:37:56: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\receive.js:120:42
    at Array.filter (<anonymous>)
    at Receive.onZigbeeEvent (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\extension\receive.js:119:65)
    at Controller.callExtensionMethod (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\controller.js:365:44)
    at Controller.onZigbeeEvent (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\controller.js:254:14)
    at Zigbee.emit (events.js:315:20)
    at Controller.<anonymous> (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\lib\zigbee.js:68:52)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (C:\Users\dyrvi\Downloads\zigbee2mqtt-master\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\controller\controller.js:523:22)
    at Generator.next (<anonymous>))

**Pull request closed without merging**
