### PR TITLE
Change Converter debug to logger.debug

### PR DESCRIPTION
**Pull request by tb-killa**
For consistency I installed the logger of Zigbee2mqtt and removed the original logger, it is not needed!

### CODE REVIEW

**Comment by Koenkk** [comment]
A library shouldn't depend on files of the application including the library. This for example given doesn't  work with @kirovilya application.

**Comment by tb-killa** [comment]
Indeed you are right :( .. thats sad because we doesn´t write logging for normal ``debug`` only our own via winston... so we doesn´t get this informations in our logging file.

we could add something like .. if (fs.existsSync(path)) -> use our debug else -> use debug (global) .
this would work with 3party ... 

another idea .. bring our logging as module ;) ?

**Comment by Koenkk** [comment]
I think that is getting a bit overkill, what is wrong with: ```DEBUG=zigbee-shepherd-converters* npm start```?

**Comment by tb-killa** [comment]
you're right, it's not for everyone.
i'm gonna close the pr with this. i don't think everyone needs it either!

**Pull request closed without merging**
