### PR TITLE
Allow search without \u0000

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Comment by Koenkk** [comment]
These `\u0000` are required (as this is the model ID)

**Comment by GermanBluefox** [comment]
As you can see, the models with zeros are still inside the array. I plan to
remove nulls from names, because of logs. The solution will just more
universal.

Koen Kanters <notifications@github.com> schrieb am So., 21. Okt. 2018,
11:45:

**Comment by Koenkk** [comment]
I probably dont understand what you are trying to accomplish. Could you explain the problem?

**Comment by GermanBluefox** [comment]
After the devices are read from  zigbee-shepherd module or some event
comes, I remove all nulls from the model names for valid logging.
It is not so nice to have nulls in the log. And I want to use the same
(without nulls) names in your module to find the devices.
To achieve it I need to store 2 names (one for log and one for search) and
with this solution only one name is required.

вс, 21 окт. 2018 г. в 18:57, Koen Kanters <notifications@github.com>:

**Comment by Koenkk** [comment]
Can you post the log containing these nulls?

**Comment by GermanBluefox** [comment]
It is about ioBroker.
[image: image.png]

вс, 21 окт. 2018 г. в 21:05, Koen Kanters <notifications@github.com>:

**Comment by Koenkk** [comment]
Image link seems to be broken.

**Comment by GermanBluefox** [comment]
image
It is not the log. But in the log it looks similar.

**Comment by arteck** [comment]
yes .. the devices inculdes this special chars.. plz merge

**Comment by Koenkk** [comment]
I think this issue should be fixed in iobroker; 

Zigbee-shepherd-converters maps the zigbee model to the actual model. e.g. `lumi.remote.b1acn01\u0000\u0000\u0000\u0000\u0000\u0000` -> `WXKG11LM`. But `lumi.remote.b1acn01` is not used as a model by the `WXKG11LM`.

**Comment by GermanBluefox** [comment]
Do you really think,  that b1acn01\u0000\u0000\u0000\u0000\u0000\u0000 is
nice for the name?
Why you don't call youself Koen\u0014Kanters?

Am Do., 22. Nov. 2018, 10:42 hat Koen Kanters <notifications@github.com>
geschrieben:

**Comment by Koenkk** [comment]
I don't think it's a nice name, but the device actually uses this name.

What is shown in IObroker is out of the scope for zigbee-shepherd-converters.

**Comment by Koenkk** [comment]
Closed due to inactivity

**Pull request closed without merging**
