### PR TITLE
added HS3SA battery reporting

### PR DESCRIPTION
**Pull request by odx**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by sjorge** [comment]
Should this fix also apply to the other 2 variants of this device?

**Comment by Koenkk** [comment]
@sjorge I will fix this once I convert it to zigbee-herdsman-converters.

**Comment by sjorge** [comment]
👍 I also had a quick peak at the newer stuff and it does look a whole lot more readable!

**Pull request merged**
