### PR TITLE
Occupancy pirOtoUdelay

### PR DESCRIPTION
**Pull request by allofmex**
This feature depends on [https://github.com/Koenkk/zigbee-shepherd-converters/pull/184](https://github.com/Koenkk/zigbee-shepherd-converters/pull/184)

Added r/w support for motion sensors msOccupancySensing -> **pirOToUDelay** setting.
This attribute is sensors timeout between "last motion detected" and "occupancy false" is reported.
(Implemented and tested for hue SML001)

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also make a PR to update the documentation? https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/information/mqtt_topics_and_message_structure.md#device-specific

**Comment by Koenkk** [comment]
And could you also change the key to `occupancy_timeout` (instead of occupancy_pirOToUDelay)?

**Comment by allofmex** [comment]
I thought about this too but was not sure if it is a good idea.
Are you sure it should be same name? occupancy_pirOToUDelay will be the timeout **inside device**, occupancy_timeout (currently, and still for other devices) is the internal "workaround" timer **in converter**. Should we mix this?

**Comment by Koenkk** [comment]
Yes, in the end it controls the same feature.

**Comment by allofmex** [comment]
fixed. docu in zigbee2mqtt follows

**Comment by MrLight** [comment]
HI allofmex,
I try to implement the sensitivity and the led indicator feature as well. Actually I always struggle with the message "No converter available for 'state' (state)". I assume that this depends on the access to the second endpoint. I really appricate, when you update the docu incl. an example how to access ep2...
Thanxs!

**Comment by Koenkk** [comment]
@allofmex, ep1 is not needed, change it to 

```
return {
                '': 2
            };
```

and it should work without any postfixes.

**Comment by allofmex** [comment]
Sorry for asking again: So [mqtt_topics_and_message_structure.md](https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/information/mqtt_topics_and_message_structure.md#device-specific) should look like this? (in Device specific?)
```
{
    // we need to use endpoint 2
    '': 2,

    // Value >= 0, 
    // This is timeout between last motion 
    // detected and sensor reports occupance: 0
    // 0 - 10: 10sec (min possible timeout) 
    //   > 10: timeout in sec
    "occupancy_timeout": 0, 
}
```

**Comment by Koenkk** [comment]
This should be enough:

```
{
    // Value >= 0, 
    // This is timeout between last motion 
    // detected and sensor reports occupance: 0
    // 0 - 10: 10sec (min possible timeout) 
    //   > 10: timeout in sec
    "occupancy_timeout": 0, 
}
```

**Comment by allofmex** [comment]
But how does zigbee2mqtt know what endpoint to use??
Its important to write this value to endpoint 2! If written to endpoint 1, device responds with status 134 (unsupAttribute)

In ioBroker I have to use
```
    occupancy_pirOToUDelay: {
        id: 'occupancy_timeout',
        prop: 'occupancy_timeout',
        ....
        epname: 'ep2',
    },
```
It does not work without epname!

**Comment by Koenkk** [comment]
I know, zigbee2mqtt will use the '' ep returned by ep() by default.

**Comment by allofmex** [comment]
I'm really sorry for bothering you:
It should **not use only** endpoint 2 for all device actions. Default should be ep 1, only for occupancy_timeout ep 2.
Sensor has other functions (illumination/temperature) that may require to use ep 1.
How to force ep for single property only? 
Like this?
`zigbee2mqtt/[device]/set {
    '': 2,
    "occupancy_timeout": 0, 
}
`
or this?
`zigbee2mqtt/[device]/ep2/set {"occupancy_timeout": 0}`
Something else?

**Comment by Koenkk** [comment]
This will only apply to the toZigbee converters and tz.generic_occupancy_timeout is the only toZigbee converter.

**Comment by allofmex** [comment]
Ok. I updated devices.js. Now we have both endpoints mentioned (for iobroker) but ep 2 as default.
zigbee2mqtt docs updated too: [https://github.com/Koenkk/zigbee2mqtt/pull/796](https://github.com/Koenkk/zigbee2mqtt/pull/796)
Ready to merge?

**Comment by Koenkk** [comment]
Yes, thanks!

**Comment by simonvanderveldt** [comment]
Thanks for adding this! Just to be sure, does one always need to set this or does it default to the correct/default hardware value (10s)?

**Comment by allofmex** [comment]
It's optional. 10s if never set.
Only difference is: before it was implemented, the timeout was 90 sec because of converters default timeout. So you may need to adjust your scripts if it relied on the 90sec.

**Comment by simonvanderveldt** [comment]
OK, clear, thanks for the clarification!

**Pull request merged**
