### PR TITLE
Add support for ubisys S1, S2, D1, J1

### PR DESCRIPTION
**Pull request by felixstorm**
General support for now, no support to configure settings yet.

Thanks!

### CODE REVIEW

**Comment by Koenkk** [comment]
Awesome, I will follow up on the configure part after I finished the zigbee-herdsman refactor.

**Comment by felixstorm** [comment]
@Koenkk Thanks! And no hurry about the configuration part - I already saw that you're currently doing a major overhaul of `zigbee-herdsman`.

Thanks for all the time and effort you put into this! This is by far the best Zigbee gateway solution available - completely open source, independent of the home automation solution used, stable, vast amount of devices supported and also good support for Zigbee features like groups, binding, reporting etc.

**Comment by Koenkk** [comment]
@felixstorm thanks for the donation!!

I was just thinking about this part. The current reason that we dont provide direct access to the zigbee object is that it would skip the queueing. However I feel that this logic shouldnt be in zigbee2mqtt and should be pushed down to zigbee-herdsman.

This allows us to give direct access to the object which will give us great flexibility.

**Comment by felixstorm** [comment]
@Koenkk You're very welcome - I would have easily spent that money and more on an off-the-shelf Zigbee gateway and functionality would surely not have been anywhere near to what Zigbee2mqtt can do.

And yes, pushing the queuing down into zigbee-herdsman definitely sounds like a good idea. But again - there is no hurry from my side. Continue your restructuring work and then in a few weeks I can contribute the configuration stuff based on the new interfaces.  
I will also need to make a few additions to the base functionality that I will try to contribute from time to time (e.g. Read / Write Attributes Structured ZCL commands as the attribute values for the button configuration on the ubisys C4 seems to get fragmented when it gets to large).

**Pull request merged**
