### PR TITLE
Xiaomi Vima Smart Lock (lumi.lock.v1)

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by dzungpv** [comment]
@kirovilya Can you share me the a sample raw data and msg.data.data['65328'] from Xiaomi Vima Smart Lock (lumi.lock.v1)?

**Comment by kirovilya** [comment]
@dzungpv https://pastebin.com/NHJYC76Y It get not from zigbee2mqtt, but you can see that it not compare with your Aqara S2 door lock

**Comment by dzungpv** [comment]
@kirovilya Yes i known, it is your modified version and you use raw hex value. I will convert string to hex for easy decode

**Comment by dzungpv** [comment]
@kirovilya Original app log the lock operation, they say in this product page: "Each operational of the lock will be automatically send to mobile phone" https://www.banggood.com/Xiaomi-Vima-Smart-Lock-Cylinder-Intelligent-Securtiy-Door-Lock-128-Bit-Encryption-w-Keys-p-1328812.html

So you must check the lock with original hub and app first

**Comment by kirovilya** [comment]
@dzungpv hmm.. thanks for the idea. but no more messages in the logs. I'll try with native hub.

**Pull request merged**
