### PR TITLE
New bulb "JIAWEN Wireless Bulb E27 9W RGBW"

### PR DESCRIPTION
**Pull request by kirovilya**
https://www.gearbest.com/smart-lighting/pp_1049610.html?wid=1433363

It can more than brightness and colortemp... but later.

ps. Please release next version.

### CODE REVIEW

**Comment by Koenkk** [comment]
Why not use `light_onoff_brightness_colortemp_colorxy` instead of `light_onoff_brightness_colortemp`?

**Comment by kirovilya** [comment]
Vendor name I get from message on pairing:
`{"type":"devIncoming","endpoints":[{"device":{"_id":3,"type":"Router","ieeeAddr":"0x00124b0014d016ab","nwkAddr":65265,"manufId":0,"manufName":"Feibit Inc co.  ","powerSource":"Mains (single phase)","modelId":"FB56-ZCW08KU1.1","epList":[11,13],"status":"online","joinTime":1529349254,`

**Comment by Koenkk** [comment]
I see, but on most chinese sites it is listed as JIAWEN. User can more easily identify when we use the same vendor name.

I think you can change the converters to `light_onoff_brightness_colortemp_colorxy` as this bulb also work with the Hue bridge. So there is a very high chance that this converters works.

Ready for merge after that.

**Comment by kirovilya** [comment]
Updated

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
