### PR TITLE
Add Busch Jaeger adaptor plug PU01

### PR DESCRIPTION
**Pull request by rutgerhendriks**
Simple adaptor plug that can turn a socket on or off

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide a link to this product? (e.g. webshop).

**Comment by rutgerhendriks** [comment]
https://www.busch-jaeger-catalogus.nl/2CKA006710A0004,artikel.html

https://busch-jaeger.schakelmateriaal.nl/tussensteker-6a-6717-84-zll.html

**Comment by Koenkk** [comment]
Thanks!

**Comment by rutgerhendriks** [comment]
@Koenkk could you add to lib/extension/homeassistant.js also the line:
'PU01': [configurations.switch],

Thanks mate ;-)

**Comment by Koenkk** [comment]
Done, supported in the latest zigbee2mqtt dev branch now.

**Pull request merged**
