### PR TITLE
added ETI device

### PR DESCRIPTION
**Pull request by ksuclipse**
Added homelite 12" puff light

### CODE REVIEW

**Comment by ksuclipse** [comment]
why did this fail the cicd check?

**Comment by Koenkk** [comment]
Is this the device? https://www.amazon.com/Hampton-Bay-1000236636-Lighting/dp/B01IGE7AAE

**Comment by ksuclipse** [comment]
This one. But I think they may be the same. Hampton Bay Lighting
https://www.amazon.com/dp/B01NAIP7JL/ref=cm_sw_r_cp_api_i_qNLKDbDZJ1X3M

**Comment by Koenkk** [comment]
Thanks, I've added this as a hampton bay light (as it's most of the times listed as such). Functional wise this doesn't matter.

**Comment by ksuclipse** [comment]
Just loaded latest-dev and that code doesn’t work anymore. Should I do a
new pull req for the new version?

**Comment by Koenkk** [comment]
Just merged it, please try again now.

**Pull request merged**
