### PR TITLE
Added Eurotronic Spirit Zigbee thermostat

### PR DESCRIPTION
**Pull request by mhelff**
Basic functions (set temperature and read/notifications of important data working.
 
Whats working:
- get heating setpoint (through occupied/unoccupied heating setpoint, push)
- get temperature selected at device (current_heating_setpoint, push)
- get battery percentage (push)
- get heating demand/valve opening (pi_heating_demand, push)
- get measured temperature at device (local_temperature, push)
- set desired temperature (through writing occupied/unoccupied heating setpoint)

Whats unclear/unsupported/not working
- systemMode off/heat -> device doesnt seem to react to write access 
- schedules (not tried)
- occupancy: read only, how to set it from outside?
- usage of occupied/unoccupied heating setpoints due to missing occupancy setting
- direct setting of current_heating_setpoint not possible (set occupied_heating_setpoint to achive that)
- there are two custom attributes (16386/16392) in the hvacThermostat cid occasionally reported, unclear what the values (1/0) mean.

### CODE REVIEW

**Comment by allofmex** [comment]
I am currently working on this thermostat too. Maybe you can include my progress in your PR too:

It's actually three custom attributes.
Attribute 16387 is the currently used temperature setting. If you change temp by device button or write to occupied/unoccupied heating setpoint, this attribute will be updated.
```
if (typeof msg.data.data['16387'] == 'number') {
    result.current_heating_setpoint =
            precisionRound(msg.data.data['16387'], 2) / 100; // Same as value on display. Is currently locked temperature
}
```
16392 seems to be similar to system_mode (will change from 1 to 5 if you press the boost button on thermostat)
```
if (typeof msg.data.data['16392'] == 'number') {
    result.system_mode_manu = msg.data.data['16392']; // 0x01 Default operation (auto?), 0x05 Boost
}
```
16386 don't know, always 0 for me.

Here the settings for toZigbee.js:
This must go to `const cfg = {}`
```
    eurotronic: { 
        manufSpec: 1,
        manufCode: 4151, 
    },
```
And the rest
 ```
  spzb0001_system_mode: {
        key: 'system_mode_manu',
        convert: (key, value, message, type) => {
            const cid = 'hvacThermostat';
            const attrId = '16392';
            if (type === 'set') {
                return {
                    cid: cid,
                    cmd: 'write',
                    cmdType: 'foundation',
                    zclData: [{
                        // 0x01 Default (Auto?)
                        // 0x05 Emergency heating
                        attrId: attrId,
                        dataType: 0x22,
                        attrData: value,
                    }],
                    cfg: cfg.eurotronic,
                };
            } else if (type === 'get') {
                return {
                    cid: cid,
                    cmd: 'read',
                    cmdType: 'foundation',
                    zclData: [{attrId: attrId}],
                    cfg: cfg.eurotronic,
                };
            }
        },
    },
```
I did not add 16387 to toZigbee since we can write to occupied/unoccupied heating setpoint to achieve the same result.

Suggest: Most of the attributes are already existing in thermostat_att_report. We should not duplicate them in eurotronic_thermostat_att_report. Just put the custom attributes in eurotronic_... and add fz.thermostat_att_report in device.js as well. (pIHeatingDemand should be added to thermostat_att_report)

Suggest2: rename hue_battery to something like generic_battery_05 // 0.5 percent steps (200=100%) instead of own eurotronic_battery_dev_change. It has same behavior.

**Comment by allofmex** [comment]
Whats still unclear/unsupported/not working

- occupancy is not  even readable for me (unsupAttribute). I don't see any way to switch between occupied/unoccupied setpoints. It will just use the one you wrote last to.
- schedule settings seems to be unsupported too
- not sure if we need all the device.bind/report settings, some (like battery) seem to be reported anyways. still testing on this
- Meaning attribute 16386
- There should be a "window open detected" attribute/mode

**Comment by allofmex** [comment]
Found bit more:
16392 are binary bits, I updated post above.

I reset my device and read afterwards the default reporting configuration:
localTemp:
`120, 1200, 25`
pIHeatingDemand, 16386, 16392
`120, 1200, 1`
occupiedHeatingSetpoint, unoccupiedHeatingSetpoint, 16387 
`120, 1200, 25`
batteryPercentageRemaining
`3600, 43200, 5`

Suggested configuration (localTemp and current_heating_setpoint reports immediately instead of minimum every 120 sec):
```
const actions = [
    (cb) => device.bind('genPowerCfg', coordinator, cb),
    (cb) => device.bind('hvacThermostat', coordinator, cb),
    (cb) => device.report('hvacThermostat', 'localTemp', 0, 600, 25, cb),
    (cb) => device.report('hvacThermostat', 16387, 1, 600, 1, cb),
];
```

We don't use the other cluster (as far as I understand), so no need to bind. Default reporting for battery should be ok already. Not sure about the heating setpoints, maybe same reporting like 16387, so we get immediate response. But not really needed, since no one else except us ourselfs will change them.

**Comment by mhelff** [comment]
@allofmex let me update my PR, i think i should also factory reset my device once - too much playing with settings yesterday.
In my opinion reporting of 16387 is important if you want to have your dashboard in HA/OpenHAB/Node-Red really reflecting the current device status.
About "system_mode_manu": I will add this, but im not sure if it is properly named. Same for my "current_heating_setpoint". Im open for suggestions.

**Comment by mhelff** [comment]
Just took a deeper look into the battery converter. Looks to me that the "hue_battery" should be "generic_battery", because it calculates percentage based on the Zigbee-Standards (0-200/2)
"generic_battery" is only used by the Ikea Tradfri-Dimmer. I will address this in a second pull request.

**Comment by mhelff** [comment]
@allofmex 
(cb) => device.report('hvacThermostat', 16387, 1, 600, 1, cb)

doesnt work for me, zigbee-sheperd tries to convert "16387" to a attribute id and crashes

**Comment by allofmex** [comment]
Yes, I noticed it too, seems we have to set reporting the manual way:
```
(cb) => device.foundation('hvacThermostat', 'configReport', [{
    direction: 0, attrId: 16387, dataType: 41, minRepIntval: 0, 
    maxRepIntval: 600, repChange: 0}], 
    { manufSpec: 1, manufCode: 4151 }, cb),
```
Looks good so far, just a few details:

Maybe we should rename `spzb_system_mode` to` eurotronic_system_mode` (and spzb0001_16386 -> eurotronic_16386) to make from/toZigbee consistent.

16386 in toZigbee.js must be `dataType: 0x20`

Please add `tz.thermostat_setpoint_raise_lower` too.

These:
```
tz.thermostat_control_sequence_of_operation, tz.thermostat_remote_sensing, 
tz.thermostat_system_mode
```
are writeable too, I just don't know if they are of any use for us (thermostat_system_mode accepts write commands, but if you read after write it is still 4)

I assume that we can use` fz.ignore_thermostat_change `instead of fz.thermostat_dev_change, else we have the messages double.

`(cb) => device.bind('genBasic', coordinator, cb)` is not needed, we do not handle any of these attributes

**Comment by mhelff** [comment]
another finding: Bit 4 in 16392 means "Off", its shown in the display after a while when the heating setpoint is much lower than the local_temperature. Received decimal value is 17, so bit 0 seems to be permanently set.

**Comment by allofmex** [comment]
Looks fine for me. (Maybe you can add Bit 4 to comments too)

**Comment by Koenkk** [comment]
Thanks!

**Comment by tfriedel** [comment]
thanks for this component!
I'm experimenting a bit with it now. I discovered you can write some values to eurotronic_system_mode:
1: heating, display normal
3: heating, display upside down
5: boost mode, valve fully open, target temperature is 30.

**Comment by mhelff** [comment]
@Koenkk @allofmex thanks for support and merging!

**Comment by mhelff** [comment]
@tfriedel yes, there seems to be a lot of undiscovered stuff. I wrote a Email to Eurotronic with some of the open questions - i hope they will answer.
@Koenkk would it make sense to add a documentation page in zigbee2mqtt?

**Comment by Koenkk** [comment]
@mhelff yes, could you add it to https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/information/mqtt_topics_and_message_structure.md#ecozy-smart-heating-thermostat-1tst-eu-bitron-wireless-wall-thermostat-with-relay-av201032 ?

**Comment by mhelff** [comment]
@Koenkk ok, i will do that in the next days!

**Comment by tfriedel** [comment]
16386 (hex 0x4002) is for errors. there's some part of a specification at the end of this document that explains it: 
https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf

here's some capabilities of the z-wave variant of this product: http://www.produktinfo.conrad.com/datenblaetter/1500000-1599999/001559295-an-01-de-EUROTRONIC_SPIRIT_Z_WAVE_PLUS.pdf

while this is not super helpful because the configuration is stored differently, the features are probably the same. i.e. there must be a way to configure how sensitive the "open window detection" is, there's probably a feature that disabled/enables backlight, possibly different energy heat modes (heat, energy heat, full power (boost) and manufacture specific. 

I believe the default mode when setting temperature via zigbee is manufacture specific and open window detection is disabled in this mode. I opened the window and it was not detected. it was however detected when I set the target temperature with the buttons on the device.

**Comment by Imperial-Guard** [comment]
Thanks for the good work! 👍  I've got one working with the dev branch, how the intergrate this with Home Assistant?

**Pull request merged**
