### PR TITLE
Support for 'FB56+ZSW1IKJ1.7' 3-gang Nue Smart Switch

### PR DESCRIPTION
**Pull request by highground88**
Confirmed working, but please check my parentheses etc @Koenkk .... I get double MQTT feedback.

It would also be great if you could support 'top' and 'bottom' in https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/devicePublish.js#L8 - is this a possibility? This would make more sense for countries like Australia where switches are mounted vertically, and give the option for the handler to match the local orientation of the device.

### CODE REVIEW

**Comment by Koenkk** [comment]
- I've added top and bottom, could you update your code?
- Could you provide a log of the double mqtt messages?

**Comment by highground88** [comment]
That's great thanks Koen. I'll eventually update the other switches too.

This is the log from startup to a single activation via MQTT:  https://pastebin.com/sje7UZK6

Message sent was `zigbee2mqtt/0x00124b0015459e77/left/set OFF`
Received back 2 messages:
`{"state_left":"OFF","linkquality":10,"state_center":"OFF","state_right":"OFF"}`
`{"state_left":"OFF","linkquality":18,"state_center":"OFF","state_right":"OFF"}`

**Comment by highground88** [comment]
Just tested some more and I get double responses for the 2-gang switch too - perhaps this is a normal QOS thing? It doesn't hurt, as both messages are the same state (but sometimes different link quality)

**Comment by Koenkk** [comment]
I've looked at the log and this is expected behaviour, the second report is from the device itself (not all devices report this), therefore zigbee2mqtt always reports this (first report).

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
