### PR TITLE
add support SA-003-Zigbee

### PR DESCRIPTION
**Pull request by stkang**
[product detail]
https://ko.aliexpress.com/item/32957480204.html?spm=a2g0o.productlist.0.0.5b4e7321varbKb&algo_pvid=a9497085-a7c0-4863-ba60-f911cb532362&algo_expid=a9497085-a7c0-4863-ba60-f911cb532362-0&btsid=bb62c063-3baf-452c-99a9-ba43e40f04a1&ws_ab_test=searchweb0_0,searchweb201602_4,searchweb201603_52

### CODE REVIEW

**Comment by stkang** [comment]
@Koenkk
please, check and merge :)

**Comment by Koenkk** [comment]
Thanks!

**Comment by johnjoemorgan** [comment]
When will this go 'live"?  Thanks

**Comment by Koenkk** [comment]
It's already in the zigbee2mqtt dev branch.

**Pull request merged**
