### PR TITLE
Refactors

### PR DESCRIPTION
**Pull request by qm3ster**
I would like to apply Prettier formatter, do you have objections to that?
The closest to the existing style would be with the following config:
```json
{
    "semi": true,
    "tabWidth": 4,
    "trailingComma": "es5",
    "singleQuote": true,
    "bracketSpacing": false,
    "arrowParens": "always"
}
```
But I would prefer the default config.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by qm3ster** [comment]
Nope as in no objections?

**Comment by Koenkk** [comment]
No objections, what will be the diff?

**Comment by qm3ster** [comment]
The default has:
```json5
{
    "tabWidth": 2,
    "singleQuote": false, // I used to hate this, but it's more consistent with HTML, Rust, pretty much everywhere. Single quote usually means `char`
    "bracketSpacing": true,
    "arrowParens": "avoid"
}
```
All of which I endorse.
However, turns out the default has
```json5
{
    "semi": true, // Not false
    // Worse for git diffs, why is this even a default?
    // This is the one time they don't give a rationale.
    "trailingComma": "none"
}
```
I forgot I had these overridden in my VSCode config, so it's clear what my opinion on semis is.
It's pretty subjective, but in my opinion Prettier solves the downsides of no-semi by giving immediate feedback in the rare case you messed up.

You write this:
```js
const a = b()
(await a).chungus()
[1, 2, 3].map()
```
Hit save:
```js
const a = b()(await a)
  .chungus()
  [(1, 2, 3)].map()
```
Yeah, this ain't it. `Ctrl-Z`, add semicolons.
```js
const a = b();
(await a).chungus();
[1, 2, 3].map()
```
Hit save:
```js
const a = b()
;(await a).chungus()
;[1, 2, 3].map()
```
It put them in such a position that the semicolon 
belongs to the line that causes the need for it, for better line-reordering diffs.

It's not unimaginable to have a different setting in your editor than the repository, and have a commit hook that formats it, but that is ofc more bothersome, eg it stops you from effectively using diffs on your dirty files.

So:
 - if you feel strongly about it, let's have semicolons
 - if you don't care, I prefer not to have semicolons

In either and all cases, do you think it should be part of travis ci?
On one hand, if someone edits on github.com / in notepad, and their change works, they'll have to format their work (if pull requests depend on lint), which slows down turnaround.
On the other hand, if unformatted code is on `master`, it being formatted simultaneously by multiple developers touching the file can cause more merge conflicts. (And generally, them formatting a part of the file they didn't touch will show up on diffs.)

**Comment by Koenkk** [comment]
I don't like adding an extra formatting step, I prefer just to edit the files as-is.

**Comment by qm3ster** [comment]
What editor do you typically use?
So, you agree to supply `.prettierrc` config for editors in the repo but not enforce that it had been run in CI?

**Comment by Koenkk** [comment]
My bad, I though you wanted to update .eslintrc.json, didn't know about Prettier. 

But as I read it's documentation, I don't think Prettier is useful for zigbee-shepherd-converters. I prefer the easy-to-edit (via github or nano) and easily creating PR's over better formatted code. This will probably end up in me correcting unaccepted PR's.

**Comment by qm3ster** [comment]
> This will probably end up in me correcting unaccepted PR's.

I totally share that sentiment, that's why I said *On one hand...*

As such, I propose that I do the following as a  PR:
- commit an `.prettierrc`
- edit `.eslintrc` to accept the output of Prettier
- do a run of Prettier on the existing codebase (making it acceptable to updated eslint)

This leaves the questions: 
1. Do you need eslint at all?
  - `.eslintrc` in the repo
  - eslint step in travis
  
    The way I see it, it's as blocking as adding Prettier to travis, which we seem to agree against.
    As a commit hook vs travis, it could `--write` the files (which *always* works on valid files, unlike `eslint --fix`) instead of attacking the user to do the fixing.
2. How bout dem semicolons?

I stumbled upon this today - [`alexjoverm/typescript-library-starter`](https://github.com/alexjoverm/typescript-library-starter)
So another option to make sure this won't add extra work on your part is automatically installed git hooks.
This is what Prettier itself says about git hooks: https://prettier.io/docs/en/precommit.html

**Comment by Koenkk** [comment]
I see, reading https://stackoverflow.com/questions/48363647/editorconfig-vs-eslint-vs-prettier-is-it-worthwhile-to-use-them-all, I guess a combination of eslint and prettier is the best solution.

**Comment by qm3ster** [comment]
Currently, I don't see any non-formatting rules in this repo.
Which rules are you concerned about?

**Comment by Koenkk** [comment]
I'm not sure if it is currently checked, but you mentioned: If you want to lint for things like == instead of ===, or other forbidden idioms,. It would also be nice to check that.

**Comment by qm3ster** [comment]
So we can add that if/when it becomes necessary. Or you mean that you'd currently want `==` to be banned?

**Comment by Koenkk** [comment]
Yes, if we make updates to the eslint/prettier configuration, `==` should be banned.

**Comment by qm3ster** [comment]
We should allow either `==null` or `==undefined`, but not both.

**Comment by Koenkk** [comment]
==null then.

**Comment by raphealjohn7** [comment]
Hello BTC

**Pull request merged**
