### PR TITLE
Support DNCKATSW001 Light Switch

### PR DESCRIPTION
**Pull request by dzungpv**
Support DNCKATSW001 Light Switch

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks! Can you provide a link/show where you bought this switch?

**Comment by dzungpv** [comment]
Now you could not buy it. I build it for my own and use privately, but i want to use it more simple with hassio, so i submit the code. It base on SampleLight in Z-stack Home 1.2.2a.44539, CC2530 chip.



Sent from my Samsung Galaxy smartphone.

**Comment by Koenkk** [comment]
Could you share some details about this? Maybe write a GithubGist about it, in that way others can also use this.

**Comment by dzungpv** [comment]
@Koenkk this is gist, you can add to the code: https://gist.github.com/dzungpv/acd00ea53446971491354bf97676378b I know you want to help if someone want to build the hardware.
But, is there anyway to change zigbee-shepherd-converters in the hassio, like put the device handle to config folder? Because some time i don't want to public and all the modification, like manufacture only provide product, not their code. Because hassio, zigbee-shepherd, zigbee2mqtt for DIY community so i think you could support private product like public product. Ofcourse i like opensource and will contribute as much as i can.

**Comment by Koenkk** [comment]
Using a docker volume you could overwrite the `devices.js` with your own.

**Comment by dzungpv** [comment]
Can you show me some relate link?
I like simplity of hassio, i like to use zigbee2mqtt hassio addon.

Is it posible to include overide device.js, fromZibee and toZigbee or load addtional array of device from file in data folder if code change? Like you set datapath in the configuration file.




-------- Original message --------

**Comment by Koenkk** [comment]
You could do this with [docker volumes](https://docs.docker.com/storage/volumes/). Just override the whole `node_modules/zigbee-shepherd-converters` with your own one from local disk.

**Comment by dzungpv** [comment]
Thank you. Can you merge this? I shared all the steps in the gist above.



-------- Original message --------

**Comment by dzungpv** [comment]
@Koenkk Yes, this is full description https://dzungpv.github.io/dnckatsw001/ include hardware, hex file and link to zigbee2mqtt

**Comment by Koenkk** [comment]
Great, thanks!

**Pull request merged**
