### PR TITLE
Support Aqua S2 Lock and Aqara Curtain

### PR DESCRIPTION
**Pull request by dzungpv**

### CODE REVIEW

**Comment by dzungpv** [comment]
All code was tested on real devices, The lock still have Latch and door state not decode, i will finish later. About the curtain if use on/off it will report state like light/switch if use upOpen/downClose it will report state of genWindows but now could not read. Lift is standard for curtain (but i have not tested it) and dim is Xiaomi custom but some time it not report state back so we will use both for complete solution. So you can merge those code

**Comment by Koenkk** [comment]
Could you respond to the questions in the TODO comments? I need this to properly integrate it with zigbee2mqtt/homeassistant.

**Comment by greynoO** [comment]
I tested some of it now:

`ZNCLDJ11LM_control_percentage`  works for opening and closing the curtain by giving a percent value (0-100), where 100 means fully open and 0 is fully closed.

I do not know what `ZNCLDJ11LM_curtain_lift` is for, as it does not seem to work.

`upOpen` and `downClose` is a standard for blind and curtain motors (hence up/open and down/close).

For `ZNCLDJ11LM_control` I had to change to lookup code to

```
const lookup = {
                'open': 'upOpen',
                'close': 'downClose',
                'stop': 'stop',
                'on': 'upOpen',
                'off': 'downClose',
            };

            value = value.toString().toLowerCase();
            if (lookup[value]) {
                value = lookup[value];
            }
```

I will test the fromZigbee part soon and would really like to get this converter to be finalized.

**Comment by Koenkk** [comment]
Closed due to inactivity

**Pull request closed without merging**
