### PR TITLE
Added state_report converter to Ksentry devices

### PR DESCRIPTION
**Pull request by gadolithium**
PR for https://github.com/Koenkk/zigbee-shepherd-converters/issues/389

### CODE REVIEW

**Comment by Koenkk** [comment]
I didn't pay good attention, but this message should already be handled by `fz.state` (https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L837)

**Comment by gadolithium** [comment]
Any way to get the converters version in the zigbee2mqtt hassio addon ? i probably have an old one

**Comment by Koenkk** [comment]
@gadolithium just update to the latest edge addon.

**Comment by gadolithium** [comment]
Closing this as it should already be handled. I couldn't test tough because the CC2530 stopped working... i'll check the tickets and open a new one if the issue is not already listed

**Pull request closed without merging**
