### PR TITLE
Remove SJCGQ11LM water leak basic (always reports true)

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Koenkk** [comment]
What does `rep` mean?

**Comment by Chrischi-** [comment]
i think it is "repeat" like your "interval" change at my PR for the magnet sensor.

**Comment by Koenkk** [comment]
Yes, although I don't understand why the name of the attribute should be changed.

**Comment by arteck** [comment]
this attribute is only "true" ..     
   
 convert: (model, msg, publish, options) => {
            return {water_leak: msg.data.data['65281']['100'] === 1};

on my water sensor... the other one is correct. therefore 2 attributes..

**Comment by Koenkk** [comment]
Then I think this converter can be removed (it has no use right?). 

I guess this also fixes: https://github.com/Koenkk/zigbee2mqtt/issues/448

**Comment by arteck** [comment]
who has dev it ?? and why ??

**Comment by Koenkk** [comment]
I probably did as I assumed this was also needed, but the `ias` report is enough. Can you remove this converter?

**Comment by ryanbeaton** [comment]
ias was not implemented when this was first added @kirovilya tipped us in https://github.com/Koenkk/zigbee2mqtt/issues/17#issuecomment-387299734 to use ias (after a zigbee shepherd update)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Notrial** [comment]
I also have the same issue with one of my two water sensors.
Should I assume that this will be fixed in the next version?

**Comment by Koenkk** [comment]
@Notrial you can test the change by using the zigbee2mqtt dev branch

**Comment by Notrial** [comment]
> @Notrial you can test the change by using the zigbee2mqtt dev branch

I'm on hassio so I don't think i can :) Please correct me if I'm wrong.

**Comment by Koenkk** [comment]
You can, use the edge branch.

**Pull request merged**
