### PR TITLE
Changed to correct external model details

### PR DESCRIPTION
**Pull request by highground88**

### CODE REVIEW

**Comment by Koenkk** [comment]
Duplicate model ID's are not allowed, perhaps the model ID of the other `HGZB-02A` is wrong?

**Comment by highground88** [comment]
I think they have re-used the model number, I don't think I had any involvement in the first handler so can't confirm exactly, but I've checked my switches and both an in-wall and single gang switch are marked with the same model. Assuming the model doesn't do anything other than report, are you happy if I rename as "HGZB-01A/02B". I realise this isn't ideal.

**Comment by Koenkk** [comment]
Yes that would be a good solution.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
