### PR TITLE
Add support for EcoSmart A19 RGB Bulb

### PR DESCRIPTION
**Pull request by boojew**
Adds support for EcoSmart RGB bulb

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you provide a link to where to buy this bulb?

**Comment by boojew** [comment]
I think theyve been discontinued - but they were sold by Homedepot.

**Comment by boojew** [comment]
Is there a difference between using generic.light_onoff_brightness().toZigbee and fz.on_off? Both seem to work, but with both the light seems to randomly stop responding.

**Comment by Koenkk** [comment]
fz = fromzigbee, tz = tozigbee, tz = commands to zigbee devices, fz = messages from devices. 

What do you mean with randomly stops responding?

**Comment by Koenkk** [comment]
Yes the generic light is the same, it's just a shortcut (https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L8).

Does this also happen when you leave a large interval (e.g. 10 seconds) between commands?

**Comment by boojew** [comment]
No - leaving it usually always guarantees it will work

**Comment by boojew** [comment]
Looking at the logs, I see this quite frequently 

`  zigbee2mqtt:error 2018-12-26 04:00:28 Zigbee publish to '0xdd16abffff070772', lightingColorCtrl - moveToColor - {"colorx":33292,"colory":15663,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.
`

**Comment by Koenkk** [comment]
This probably indicated a bad connection, does this still happen when having it close to the coordinator?

**Comment by boojew** [comment]
Yes - they are about 10’ from one another.

**Comment by Koenkk** [comment]
That's indeed strange, with what hub is this device normally used? Perhaps it's not completely following the ZCL specs.

**Comment by boojew** [comment]
They advertise as Wink compatible, but also works w/ Hue.

**Comment by Koenkk** [comment]
Can you try with changing this line: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js#L9 to `disDefaultRsp: 1,`

**Comment by boojew** [comment]
Tried it - and I now get the following error and the light is completely unresponsive

` zigbee2mqtt:debug 2018-12-29 21:49:51 Received MQTT message on 'zigbee2mqtt/0xdd16abffff070772/set' with data '{"state": "ON", "color": {"x": 0.189, "y": 0.284}}'
  zigbee2mqtt:error 2018-12-29 21:50:19 Zigbee publish to '0xdd16abffff070772', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":1} - null failed with error Error: Timed out after 30000 ms`

**Comment by Koenkk** [comment]
Ok, I'm lost on how to solve this problems. Besides the errors is anything else not working?

**Comment by boojew** [comment]
The device is occasionally very slow to respond.. Other than that - it
works.

**Pull request merged**
