### PR TITLE
lumi.plug and lumi.ctrl_86plug.aq1 has same events

### PR DESCRIPTION
**Pull request by kirovilya**
may be bug in name "lumi.ctrl_86plug" without "aq1", or it other device?

### CODE REVIEW

**Comment by Koenkk** [comment]
What is the model number written on the device?

**Comment by kirovilya** [comment]
When joined, I get device info:
```
"type":"Router",
"ieeeAddr":"0x00158d0002013645",
"nwkAddr":12298,
"manufId":4447,
"manufName":"LUMI",
"powerSource":"Mains (single phase)",
"modelId":"lumi.ctrl_86plug.aq1",
"epList":[1,2,3],
```

**Comment by kirovilya** [comment]
Or you mean "QBCZ11LM" ?

**Comment by Koenkk** [comment]
I have a QBCZ11LM with model id lumi.ctrl_86plug, so it seems that this device uses multiple model ID's. Will update this.

**Comment by kirovilya** [comment]
Updated

**Pull request merged**
