### PR TITLE
Introduce Ninja Smart plug to devices.js

### PR DESCRIPTION
**Pull request by asgothian**
Implement support for Ninja Smart plug from Ninja Blocks Inc.

Support for ON/OFF and power metering.

### CODE REVIEW

**Comment by Koenkk** [comment]
I think this is a Netvox plug (branded as Ninja Blocks Inc.?)(http://www.computex.biz/PhotoPool2/201504/201504281705364222.pdf). Can you confirm this?

**Comment by asgothian** [comment]
It does look like it. I will see if i can access it as the Netvox Plug and use the identical code.
Not sure if i will be able to do this tonight, though.

**Comment by Koenkk** [comment]
@asgothian my guess is that this is exactly the same as https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L1510 but then the EU version.

**Comment by asgothian** [comment]
I did run a test trying to use it as the Netvox Plug by adding the Ninjas identifier to the netvox block:
 
zigbeeModel: ['Z809AER'] to 
zigbeeModel: ['Z809AE3R', 'Ninja Smart plug'],:

I did get the message Failed to configure 0x00137a000001a9b0 Ninja Smart plug, and the metering did no longer work.

I would assume that the hardware is the same, but that Ninja Blocks did some of their own firmware stuff.

A.

**Comment by Koenkk** [comment]
Can you provide a link to this device? (url web link)

**Comment by asgothian** [comment]
Unfortunately not, as the company went bankrupt 2015. I assume there is no more web link. People like me, who backed their Kickstarter or bought in early might have them lying around, though.
What i do have is the link to their Kickstarter, which is where i got it from:
https://www.kickstarter.com/projects/ninja/ninja-sphere-next-generation-control-of-your-envir?ref=nav_search&result=project&term=Ninja%20Sphere

What i can also provide is 3 images - they look very much like the plug you linked. 

screen shot 2019-02-03 at 18 42 01
screen shot 2019-02-03 at 18 40 30
screen shot 2019-02-03 at 18 40 16

I did a few more tests, and was able to confirm that the plug does not support the haElectricalMeasurement Cluster. Attempting to read it returns 
unsupAttribute {"msg":[{"attrId":0,"status":134}]}
while reading the seMetering Cluster returns
success {"msg":[{"attrId":0,"status":0,"dataType":37,"attrData":[0,2]}]}

**Comment by Koenkk** [comment]
Ok, thanks for figuring this out!

**Pull request merged**
