### PR TITLE
Added Heiman HS1CG-M Combustible Gas Sensor

### PR DESCRIPTION
**Pull request by WoLpH**
http://www.heimantech.com/product/76.html

I believe it's the successor of the HS3CG but I'm not entirely certain

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Filipok-A** [comment]
Hi @WoLpH,
I have the same sensor but the model on it is HS1CG-E and it identifies by Zigbee model 'GASSensor-EM'.   Would be great if you can add it to the model list.

Thanks!

**Comment by WoLpH** [comment]
@Filipok-A I can add it if you can give me some debug logs while adding the device. Just to be sure it's the same thing with the same support :)

Alternatively, it's just a few lines to change/copy so you can easily test if it works for you by changing 2 lines: https://github.com/Koenkk/zigbee-shepherd-converters/pull/543/files#diff-6c9a6acf22f90d1c6e524d9f3c5c1745R3443-R3444

**Comment by Filipok-A** [comment]
I have been using it by adding this model to the config of HS3CG, and it works fine.  And from what I see the config is identical to HS1CG.

**Pull request merged**
