### PR TITLE
Support for DIY devices: DNCKATSW002, DNCKATSW003 and DNCKATSW004

### PR DESCRIPTION
**Pull request by dzungpv**
I create more DIY device base on DNCKATSW001, CC2530. It support from 1 button to 4 buttons (with relay)
You can see more detail here https://github.com/dzungpv/dnckatsw00x/blob/master/README.md

### CODE REVIEW

**Comment by tb-killa** [comment]
I´m also working on DIY Hardware with CC2530 Module, nice work you do :)

If every of your ``DNCKAT_XXX`` Device has the same ``_state`` converter function for ``attReport`` , please provide only one of this and name it ``DNCKAT_Sxxx_state`` in ``fromZigbee.js`` and use this ones in multiple ``devices.js`` entrys to avoid duplications =)

**Comment by dzungpv** [comment]
I will improve it. But since i just want to make it quick, just make it fisrt running. You can see my project and two in the readme, it is very useful.

**Comment by Koenkk** [comment]
Good!:) After you've merged the converters I will merge it.

**Comment by dzungpv** [comment]
@Koenkk it should OK now, thank you.

**Comment by Koenkk** [comment]
@dzungpv thanks!

**Comment by Koenkk** [comment]
@danielwelch are there any hassio images available of the dev branch? I see there is and [edge image](https://hub.docker.com/r/dwelch2101/zigbee2mqtt-edge-armhf/tags/) but this hasn't been updated recently.

**Comment by danielwelch** [comment]
@Koenkk Would it be better to have the edge version track the dev branch than the master branch, as it does now?

If the image hasn’t been updated recently, something must be going on the build trigger from your node script -> triggering a build on Travis -> the distribution script run by Travis pipeline. I imagine there’s a problem with the logic in my build/distribute script for Travis relating to the edge version, probably a silly mistake somewhere. I’ll try to take a look later today.

**Comment by Koenkk** [comment]
@danielwelch great! it indeed makes sense to have `dev` -> `edge`. Let me know if I need to do something :smile:

**Pull request merged**
