### PR TITLE
Update devices.js

### PR DESCRIPTION
**Pull request by kimonm**
Added support for GE 45852 wall dimmer plug, and Sengled Element classic bulb

### CODE REVIEW

**Comment by Koenkk** [comment]
When dimming the switch using the button on the device, is this also reported? I would expect the same for `genLevelCtrl` as you do for `genOnOff`.

**Comment by kimonm** [comment]
I just added code to devices.js below.  I don't see any messages sent when manualy dimming using the button on the plug. From DEBUG=* npm start, I think the relevant debug messages are:

  zigbee2mqtt:zigbee Check online 0x0022a300001af090 +0ms
  zigbee-shepherd:request REQ --> ZDO:nodeDescReq +18s
  cc-znp:SREQ --> ZDO:nodeDescReq, { dstaddr: 56148, nwkaddrofinterest: 56148 } +18s
  serialport write 9 bytes of data +18s
  cc-znp:SRSP <-- ZDO:nodeDescReq, { status: 0 } +11ms
  cc-znp:AREQ <-- ZDO:nodeDescRsp, { srcaddr: 56148, status: 0, nwkaddr: 56148, logicaltype_cmplxdescavai_userdescavai: 1, apsflags_freqband: 64, maccapflags: 142, manufacturercode: 4388, maxbuffersize: 82, maxintransfersize: 255, servermask: 0, maxouttransfersize: 255, descriptorcap: 0 } +22ms

**Added to devices.js:**

 device.bind('genLevelCtrl', coordinator, (error) => {
                    if (error) {
                        callback(error);
                    } else {
                        device.foundation('genLevelCtrl', 'configReport', [cfgRptRec]).then((rsp) => {
                            callback(rsp[0].status === 0);
                        });
                    }
                });

**Comment by Koenkk** [comment]
Ok, so adding `genLevelCtrl` has no advantage?

**Comment by kimonm** [comment]
No, it didn't. Tonight I'll try adding the code on the wiki to just report messages from a device (e.g., like shown below). However, if there's some specific code you'd like me to try, just let me know. 

I'll add something like the following to fromZigbee.js, edit devices.js, and see if it reports anything on dimming with the button:

xiaomi_temperature: {
    cid: 'msTemperatureMeasurement',
    type: 'attReport',
    convert: (model, msg, publish, options) => {
        console.log(msg.data)
    },
},

**Comment by Koenkk** [comment]
When there are no `WARN No converter available for..` it makes no sense to add anything to `fromZigbee.js`.  I think it's ready for merge.

**Pull request merged**
