### PR TITLE
Calibration

### PR DESCRIPTION
**Pull request by allofmex**
Added option to calibrate reported values.

Implemented same way as `_precision`. Use as option `temperature_calibration: -1.4` to adjust reported temperature values by 1.4 degree. 
_Background: My 5 hue motion sensor differ by 3.5 (!) degree on temperature messurement if you place them right next to each other._

Same with `illuminance_calibration` and `pressure_calibration`.

Added for `generic_` converter so far. May be added to other converter as well.

For **illuminance**:
Linear instead of absolute calibration offset. Cal-Value is for 10 000 lux. 5000lux will be offset by 50% of cal-value. Else a completely dark room would report -200lux, if calibration value is -200.

### CODE REVIEW

**Comment by Koenkk** [comment]
Awesome!

For the illuminance, I was wondering if it is more intuitive to provide a percentage (e.g. 0.9 = 90%) instead of 10 000 = 100% ?

**Comment by allofmex** [comment]
> more intuitive to provide a percentage

Good idea. Thats better.

**Comment by allofmex** [comment]
>  provide a percentage

Done.

Since calibration value may be usually small percentage number only, I use percent values like -0.05 (%) instead of 0.0005 (of 1.0=100%). Should be better readable.

Ok?

**Comment by Koenkk** [comment]
Looks good, thanks!

**Pull request merged**
