### PR TITLE
Support hold event for QBKG04LM (Aqara single light switch)

### PR DESCRIPTION
**Pull request by poma**
Added support for hold event in the same way as it's done for QBKG03LM. I have both devices and was able to test it - looks like it works well.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by poma** [comment]
About naming: `button_single` was consistent with other (double button) aquara switch

Existing click events for 2 button switch are: `left`, `right`, `both` and for single button `single`

Existing hold events for double button are `button_left`, `button_right`, `button_both`

I think `button_single` is kinda logical in this context.

**Comment by Koenkk** [comment]
I understand your reasoning, but for the QBKG04LM `click` is currently used (https://github.com/poma/zigbee-shepherd-converters/blob/724faba6b3210ff8130bcb9206928b479d468798/converters/fromZigbee.js#L967) which makes `action` more logical to me.

**Comment by poma** [comment]
Yes, it is `{click: 'single'}` for this and for double button `{click: 'left'}`, ``{click: 'right'}`, `{click: 'both'}`

Hold events for double button `{button_left: 'hold'}` etc.

**Comment by Koenkk** [comment]
I understand, but also for other things like this we use `action` (e.g. https://github.com/poma/zigbee-shepherd-converters/blob/724faba6b3210ff8130bcb9206928b479d468798/converters/fromZigbee.js#L523). I see the QKBG03LM is an exception instead of the default (we have to because of 2 endpoints). This would be the first time we will use `button_single`. 

If you really think this would be more logical please make a new PR and I will accept it.

**Comment by poma** [comment]
Nah just wanted to make sure you get the full context for this. If you think `action` is better I'm ok with that.

**Pull request merged**
