### PR TITLE
osram flex rgbw

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

Is there any model number written on the strip?

**Comment by sinalco92** [comment]
I have the Osram Stip. 
This is the Model No. 4052899926110

You can finde it on the datasheet: 
https://www.led.de/media/pdf/ff/3d/46/datenblatt_10051_osram_lightify_flex_rgbw_flexibler_led_strip.pdf

**Comment by arteck** [comment]
plz merge

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
