### PR TITLE
Experimental ecozy support (WIP, re-working)

### PR DESCRIPTION
**Pull request by sebastianheierhoff**

### CODE REVIEW

**Comment by Koenkk** [comment]
Is it also possible to set temperatures via zigbee? These should be added to the toZigbee converters.

**Comment by sebastianheierhoff** [comment]
Not yet. Basically there should be two options to set temperatures:
-  a) via Setpoint Raise/Lower Command ([ZigBee Cluster Library Specification,](http://www.zigbee.org/~zigbeeor/wp-content/uploads/2014/10/07-5123-06-zigbee-cluster-library-specification.pdf) p. 384) or 
- b) directly by setting the OccupiedHeatingSetpoint Attribute (p. 374).

I opted for the second and noticed that we were missing the Attribute Write function for that. I did just finish to implement it, when I found your code in https://github.com/Koenkk/zigbee2mqtt/commit/7c349d18036b2af3dfd0782ca065afc05c67128d. I will use your snippet and hope to finish this by the end of the weekend.

**Comment by tb-killa** [comment]
Hi @sebastianheierhoff 
Nice work 👍 i see you bring in so much support .. thanks a lot.

I see you ported all binding and reporting:
Don´t know why ..but from my two devices in the past the reporting for voltage doesn´t work.
Thats because i remove them:
``
zigbee2mqtt:debug 2018-8-27 21:26:32 Configured '(cb) => device.report('genPowerCfg', 'batteryVoltage', 600, 21600, 0x01, cb)' with result 'unreportableAttribute'
``
See my results from https://github.com/Koenkk/zigbee2mqtt/issues/129#issuecomment-405040153

```
hvacThermostat pIHeatingDemand result { Error: Timed out after 30000 ms
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/q/q.js:1846:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'ETIMEDOUT' }
hvacThermostat localTemp result null
hvacThermostat occupiedHeatingSetpoint result unreportableAttribute
hvacThermostat systemMode result unreportableAttribute
hvacUserInterfaceCfg keypadLockout result unreportableAttribute
hvacUserInterfaceCfg tempDisplayMode result unreportableAttribute
genPowerCfg batteryVoltage result unreportableAttribute
2018-7-14 20:02:50 ERROR Failed to configure 0x70b3d5de00000e2a
```

Does this is reportable for you ?`

**Comment by sebastianheierhoff** [comment]
Hi @tb-killa,

thanks for pointing this out. I have to admit, that I hadn't read your comment in detail. device.report on 'batteryVoltage' fails, because the attribute is not reportable according to the zigbee specification. 'batteryPercentageRemaining' should be reportable, but apparently isn't supported by ecozy ( device.report('genPowerCfg', 'batteryPercentageRemaining', 600, 21600, 0x01, cb)' with result 'unsupAttribute'). From my point of view, that's a pity for we won't be able to see when a battery needs changing. All other attributes work fine.

Kind Regards,
Sebastian

**Comment by sebastianheierhoff** [comment]
Sorry for the mass of commits. Still struggling with git and JavaScript ;). Setting temperatures via zigbee/ mqtt does now work.

**Comment by tb-killa** [comment]
Nice work .. if i got some more free time at the end of this month (hope) ... i will check your code on live :)
I´m thinking about needing extension:

report and write for 'hvacThermostat'-'runningState'
-> Result if eg : relais or other is running
report and write for 'hvacThermostat'-'systemMode'
-> Result if Off or Auto or Heat ...
report and write for 'hvacUserInterfaceCfg'-'keypadLockout'
-> Result if Keypad is locked

**Comment by lukasz-h** [comment]
Could you please write MQTT topic and message that can control temperature? I was trying to find it out by myself, however without any success.

**Comment by sebastianheierhoff** [comment]
Sure. If you are running the latest version of this pull request, there are two options for setting the temperature. Both messages need to be send to mQTT topic <YOUR DEVICE ID>/set. The payloads are: 
a) '{"occupiedHeatingSetpoint":<TEMPERATURE IN CELSIUS>} e.g. {"occupiedHeatingSetpoint":23}
or 
b) '{ setpointRaiserLower: '{ "setpointRaiseLower": {"mode": "0x00", "amount": "<AMOUNT CELSIUS BY WHICH TO RAISE OCCUPIEDHEATINGSETPOINT>"}}' e.g. { setpointRaiserLower: '{ "setpointRaiseLower": {"mode": "0x00", "amount": "1"}}

**Comment by lukasz-h** [comment]
When I want to use method a):
`mosquitto_pub -h xxxxx -t "zigbee2mqtt/sypialnia_grzejnik/set" -m '{"occupiedHeatingSetpoint":22}'`
zigbee2mqtt crashes:
```
zigbee2mqtt:info Mon Sep 17 2018 20:04:00 GMT+0200 (CEST) Zigbee publish to '0x70b3d5de0000094a', hvacThermostat - undefined - undefined - null
/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:326
        throw new TypeError('zclData should be an object or an array');
        ^

TypeError: zclData should be an object or an array
    at Object.af.zclFunctional (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:326:15)
    at ZShepherd._functional (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:671:20)
    at Endpoint.ep.functional (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:539:25)
    at Zigbee.publish (/opt/zigbee2mqtt/lib/zigbee.js:194:16)
    at Object.keys.forEach (/opt/zigbee2mqtt/lib/controller.js:523:25)
    at Array.forEach (<anonymous>)
    at Controller.handleMQTTMessageDevice (/opt/zigbee2mqtt/lib/controller.js:498:27)
    at Controller.handleMQTTMessage (/opt/zigbee2mqtt/lib/controller.js:343:18)
    at MQTT.handleMessage (/opt/zigbee2mqtt/lib/mqtt.js:73:18)
    at emitThree (events.js:136:13)
```
Do you have any idea what I'm doing wrong?

**Comment by lukasz-h** [comment]
zigbee2mqtt/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:
```
...
    thermostat_occupiedHeatingSetpoint: {
        key: 'occupiedHeatingSetpoint',
        type: 'write',
        attr: ['occupiedHeatingSetpoint'],
        convert: (value, message, model) => {
            return {
                cid: 'hvacThermostat',
                attrid: 'occupiedHeatingSetpoint',
                data: Math.round(value) * 100,
            };
        },
    },
...
```
Maybe I did something wrong during updating zigbee-shepherd-converters, I have no experience in nodejs and npm at all. I have just clone that repo, update to pull request and copy everything to zigbee2mqtt/node_modules/zigbee-shepherd-converters is it ok?

**Comment by sebastianheierhoff** [comment]
You're absoutely right. The PR should be renamed and redone. I have already started re-working this using foundation write from https://github.com/Koenkk/zigbee2mqtt/pull/355. HBUniversalCFRemote did implement a write command, which I used. I should probably not have merged the whole branch.

**Pull request closed without merging**
