### PR TITLE
Add Yale YRD226HA2619 Support

### PR DESCRIPTION
**Pull request by moistgun**
Added device entry in the Device.js and an entry in the fromZigbee.js since this lock uses a different 'type' than the current supported device.

### CODE REVIEW

**Comment by moistgun** [comment]
I'm not familiar with Github, CI, or branch merging enough to know what to do now.

Yale YRD226HA2619 locks work with these changes.

**Comment by Koenkk** [comment]
Thanks!

**Comment by epicurean70** [comment]
sorry, newbie question. but how do I pair this with zigbee2mqtt? I just installed the zigbee2mqtt docker, and am using openhab

**Comment by moistgun** [comment]
From memory, you 'log in' with the master password on the lockpad, and press the gear instead of the check mark.

From there, if the device recognizes the zigbee module, you have the ability to press seven.

then press one

**Pull request merged**
